### ISSUE TITLE
Kerbalism support: nuclear reactor/fuel processor

### ISSUE THREAD

**Issue by Shiolle** [Nils277/KerbalPlanetaryBaseSystems#104]
K&K Nuclear Reactor and K&K Centrifuge are missing a radiation source node when using Kerbalism. I am not sure yet if they work with Kerbalism's timewarp resource processing system.

Kerbalism version 3.0.2
Planetary Base Systems version 1.6.9
KSP version 1.7.3 with both expansions.
![Radiation](https://user-images.githubusercontent.com/16443003/61407795-3e70c380-a8e7-11e9-831e-6fabe96863c6.jpg)

**Comment by Shiolle** [comment]
Here is my own attempt at fixing the issue. The file goes into GameData\PlanetaryBaseInc\ModSupport\Configs\Kerbalism\

[KPBS_MM_Kerbalism_Radiation.zip](https://github.com/Nils277/KerbalPlanetaryBaseSystems/files/3403878/KPBS_MM_Kerbalism_Radiation.zip)

**Comment by Nils277** [comment]
Thanks a lot for the patch. It was added to in release 1.6.10 with commit 687e016

**Comment by darco89** [comment]
Hello everyone, I saw the post was mentioning the relevant parts and the mod Kerbalism... the K&K Nuclear Reactor currently is having troubles with Kerbalism. it seems to recharge the batteries but at no EnrUranium cost... Is it only in my save? Cheers!
