### ISSUE TITLE
Is there a way to symmetrically add tanks to all slots of the "Inline 4x Storage" part?

### ISSUE THREAD

**Issue by rmccreary** [Nils277/KerbalPlanetaryBaseSystems#105]
When I was playing with the mod, I wasn't able to figure out how to attach tanks to all positions of the 4x Storage part without them looking [wonky](https://user-images.githubusercontent.com/5460609/64131140-51066580-cd8c-11e9-8302-4ce70ab0ef1a.png).

My solution was to add `node_stack_b = -0.55, 0, 0.55, 0, 0, 1, 1` to each of the tank parts.

It needs more tweaking to get it to look just right, but [this is the result](https://user-images.githubusercontent.com/5460609/64131311-57e1a800-cd8d-11e9-8c75-ccc4dc5ab84c.png). I'm not sure exactly what values to use for the position because I'm unfamiliar with editing models and modding in general. It takes a while to restart KSP each time to test them.

It's possible that I'm missing something in the vehicle editor or I've completely missed how these parts are supposed to work.

**Comment by Nils277** [comment]
Hmm, the attachment nodes on this part should be in a way so that the container all fit neatly inside them...I will review that and post screenshots in the case they are there and you missed something ;-)

**Comment by Nils277** [comment]
Closing this one. Just verified that the parts can be added in all orientation to make them fit symmetrically into the 4x Storge part without any modifications to the stack nodes.
If they should still cause troube, please re-open.
