### ISSUE TITLE
Factory Parts

### ISSUE THREAD

**Issue by SteveBenz** [Nils277/KerbalPlanetaryBaseSystems#107]
My mod, [Progressive Colonization System](https://github.com/SteveBenz/ProgressiveColonizationSystem), has been leveraging the KPBS parts with some success for a year now, and I'm finally starting to make my own parts.  I've just completed making a couple parts that are for orbital use; my next target is industrial parts.  I've just been re-cfg'ing the stock ISRU so far.

KPBS contains a few parts along those lines (e.g. the ISRU and, the EPL smelter & workshop).  But they're special purpose (e.g. the EPL logos emblazoned upon them) or they're something you'd just need on any base (the ISRU).

I _could_ create some parts like that and bolt them into my mod, but I feel like my mod, at its heart, is not a parts-pack, it's a behavior-pack.  Yours is the parts pack, so I feel like I should contribute them to your mod and use them in mine.  I'd endeavor to make the parts generic - so somebody else could repurpose them for their own mods.

If you're interested, great, I'll let you know when I have a thing to share.  If not, that's cool.  Could be that once you see what I've done your answer will change; either way, I won't get bent.

But either way, I'd love to have something I could import into Blender that would be the exact profile for K&K endcaps.  Is there another repo where you keep 3d model sources that I could just download?

**Comment by Nils277** [comment]
Hey, sorry for the late reply. I have been quite absent from KSP for a while. If you still like i can give you Blender files which have the same profile of the KPBS parts. I can also add the models to KPBS as support for your Progressive Colonization System mod. :)

**Comment by Nils277** [comment]
Seems to be outdated. Please re-open or pm me when you want to have some part templates or similarö
