### ISSUE TITLE
Missing parts after updating to KSP 1.9.1

### ISSUE THREAD

**Issue by psychonaut25** [Nils277/KerbalPlanetaryBaseSystems#109]
Today I decided to update all of my mods to the KSP 1.9.1 versions, and when I attempt to load my save file I am asked if I'm sure I want to load the save, because several active vessels are missing certain parts.

Some of these were from NearFutureSolar, and I found [this issue](https://github.com/ChrisAdderley/NearFutureSolar/issues/77) on the Github page for that particular mod, and I solved the problem using the advice found here.  However, one of these missing parts is called KKAOSS.KIS.FuelTank, and I can't seem to find it anywhere.

Can anybody point me in the right direction here?  I just want to load my save file in the latest version of KSP, but now I'm having to hunt down multiple missing parts from multiple mods.

**Comment by Nils277** [comment]
the KKAOSS.KIS.FuelTank is a Canister from Kerbal Planetary Base Systems, that is only available when Kerbal Inventorry System (KIS) is installed:
https://www.curseforge.com/kerbal/ksp-mods/kerbal-inventory-system-kis

**Comment by psychonaut25** [comment]
Ah, thank you, that makes sense.  I had removed KIS because I so rarely use it and it was giving me TweakScale FATAL errors, but I will have to take that up with Lisias after I finish recovering all of my other old parts from other mods.

Much appreciated
