### ISSUE TITLE
Algae farm ore consumption.

### ISSUE THREAD

**Issue by Dr-Farnsworth** [Nils277/KerbalPlanetaryBaseSystems#11]
The Algae farm consumes LOTS of ore.
 I am trying to run a closed loop base on Minmus and be able to build craft and base structures with EPL. The algae farm consumes so much ore that my workshop starves for ore and shuts down. There are already 11 ore drills operating in my base to provide for it's needs. Water from your drills and mulch from Kerbal, umm... stuff, should make algae.
Please consider taking ore out of the supply chain for the algae farm.

**Comment by Nils277** [comment]
Hi,
what life support mod are you using?
For USI-LS, the algae farm consumes 250 times less ore than the stock ISRU, so it shouldn't have such a big impact. For TAC LS it is even way less than that.
How many algae farms are you using in your base?

**Comment by Dr-Farnsworth** [comment]
I am using MKS Lite and USI Life Support. 
I can turn off the MKS workshop and run one of the algae farms. With The ISRU and workshop running, all of the available ore is being consumed so even the small amount needed for the algae farm is unavailable. I could always turn off the workshop but the whole point of the remote base is to be able to build vehicles with Extraplanetary Launchpads. 

I have three Kerbals in the base making mulch. When the KPBS greenhouse is farming, there is only enough mulch to supply one algae farm. If I start a second algae farm, it will indicate that there is not enough mulch.
When the one algae farm is operating in a base with three kerbals, the fertilizer level increases slowly.

The fertilizer level increases much faster when I use the MKS Lite dirt drills and crush-o-matic.
A higher fertilizer production rate is a huge benefit since the fertilizer is used to supply agroponic systems in the orbiting station and other vehicles.

**Comment by Nils277** [comment]
Sorry for the long wait. Have been incative for KSP a while.
To prevent the Workshops from using all the Ore, try to put the algae farm and an additional drill in a part of the base that is separated by a docking port or a similar part that allows you to stop the fuel flow. When the fuel flow is stopped it should be possible that both work simutaneously. (Take care that all other resources also have to be in the right part of the base).

Regarding the much higher fertilizer production of MSK Lite: The parts for USI LS of this mod are designed to work on their own. There is no real compatibility (as in: they are not balanced against each other) with MKS or MKS-Lite as of yet. You can try out some semi-official patches for KPBS that are posted in the mod's thread in the KSP forum. Or look here:
https://github.com/DanStaal/DStaal_UKS_KPBS_Addons/releases
Please note that this patch is intended for MKS and not MKS-Lite so your experience might not be as expected ;)

**Comment by Nils277** [comment]
I think with the well worked out patch for KPBS-MKS interaction and the integration of MKS-Lite into MKS this issue is not longer relevant. If there still persists a problem using MKS together with KPBS, please consider creating a bug report for the patch :)
