### ISSUE TITLE
Update to KSP 1.11.1

### ISSUE THREAD

**Issue by michielboekhoff** [Nils277/KerbalPlanetaryBaseSystems#120]
Hi there,

I love this mod! It's absolutely fantastic. I'd love it if this mod were compatible with 1.11.1 so I could upgrade to that. If there's anything I can do to help, please do let me know.

**Comment by Nils277** [comment]
The mod is already usabel with KSP 1.11.1 and 1.11.2
In the near future, it will get an official version for 1.11.2

**Comment by Nils277** [comment]
Done with c54946f
