### ISSUE TITLE
version mismatch error on 1.12.3

### ISSUE THREAD

**Issue by byt3c** [Nils277/KerbalPlanetaryBaseSystems#130]
"KSP_VERSION_MAX": {
        "MAJOR": 1,
        "MINOR": 11,
        "PATCH": 9
    },
entry causes compatibility error - unless statement of 1.12 compatibility is exaggerated :)

**Comment by Nils277** [comment]
thanks for the hint, updated the file in the repository with 63c5a54. Updated packaged version will follow soon

**Comment by Nils277** [comment]
fixed in [dcc90e1](https://github.com/Nils277/KerbalPlanetaryBaseSystems/commit/dcc90e1147931a8a24a0d5073ef95f8d5d0bf7b7)
