### ISSUE TITLE
K&K garage cover bug

### ISSUE THREAD

**Issue by NRobbo** [Nils277/KerbalPlanetaryBaseSystems#131]
K&K Garage cover cant be removed from the build area once pulled out. cant be deleted either, very annoying.

mod v: 1.6.14
KSP v: 12.2.3.3173

**Comment by RuniTails** [comment]
I have the same issue.
I looked at the logs and found this when placed and tried to click on adapter:
`[LOG 09:36:14.631] Garage_To_MK3 added to ship - part count: 4`
`[EXC 09:36:15.833] ArgumentOutOfRangeException: Length cannot be less than zero.
Parameter name: length
	System.String.Substring (System.Int32 startIndex, System.Int32 length) (at <9577ac7a62ef43179789031239ba8798>:0)
	EditorLogicBase.CreateSelectedPartIcon () (at <4deecb19beb547f19b1ff89b4c59bd84>:0)
	EditorLogic.<SetupFSM>b__189_20 (KFSMState st) (at <4deecb19beb547f19b1ff89b4c59bd84>:0)
	KerbalFSM.updateFSM (KFSMUpdateMode mode) (at <4deecb19beb547f19b1ff89b4c59bd84>:0)
	KerbalFSM.UpdateFSM () (at <4deecb19beb547f19b1ff89b4c59bd84>:0)
	EditorLogic.Update () (at <4deecb19beb547f19b1ff89b4c59bd84>:0)
	UnityEngine.DebugLogHandler:LogException(Exception, Object)
	ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(
Exception, Object)
	UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)`

Log file: [KSP.log](https://github.com/Nils277/KerbalPlanetaryBaseSystems/files/8192143/KSP.log)

**Comment by Nils277** [comment]
Fixed in [dcc90e1](https://github.com/Nils277/KerbalPlanetaryBaseSystems/commit/dcc90e1147931a8a24a0d5073ef95f8d5d0bf7b7)
