### ISSUE TITLE
Part "KKAOSS_LS_container_carbon_extractor" as invalid "tag" entry.

### ISSUE THREAD

**Issue by Galenmacil** [Nils277/KerbalPlanetaryBaseSystems#14]
Log excerpt:

[LOG 22:57:12.295] PartLoader: Compiling Part 'PlanetaryBaseInc/ModSupport/Parts/LifeSupport/Container_CarbonExtractor/KKAOSS_LS_container_carbon_extractor'
[WRN 22:57:12.296] PartLoader Warning: Variable tag not found in Part

line 38 read: "tag = Carbon Extractor"

it should probably read: "tags = carbon extractor"

Note the missing 's' at the end of tag.

**Comment by Galenmacil** [comment]
Part "KKAOSS_LS_container_waterpurifier" also contain the invalid entry.

**Comment by Nils277** [comment]
Uploaded fix in commit [8eb669dc8e1bf8dae3a744ecac39cc5ddaf8064e](https://github.com/Nils277/KerbalPlanetaryBaseSystems/commit/8eb669dc8e1bf8dae3a744ecac39cc5ddaf8064e)

Will be part of the next update. Thanks for the report!
