### ISSUE TITLE
Part "KKAOSS_Water_OrbitalScanner" generate an error on load.

### ISSUE THREAD

**Issue by Galenmacil** [Nils277/KerbalPlanetaryBaseSystems#15]
Excerpt from the log file:

_[LOG 22:57:12.787] PartLoader: Compiling Part 'PlanetaryBaseInc/ModSupport/Parts/LifeSupport/OrbitalScanner/KKAOSS_Water_OrbitalScanner'
[ERR 22:57:12.789] Cannot find a PartModule of typename 'ModuleHighDefCamera'_

**Comment by Nils277** [comment]
Uploaded fix in commit [8eb669dc8e1bf8dae3a744ecac39cc5ddaf8064e](https://github.com/Nils277/KerbalPlanetaryBaseSystems/commit/8eb669dc8e1bf8dae3a744ecac39cc5ddaf8064e)

Will be part of the next update. Thanks for the report!
