### ISSUE TITLE
Packaging goof?

### ISSUE THREAD

**Issue by Kerbas-ad-astra** [Nils277/KerbalPlanetaryBaseSystems#17]
The KPBS_MM_KeepFit.cfg in the 1.3.0 release zip is missing the CRY-5000Freezer and KKAOSS_garage_adapter_g_2 entries.

**Comment by Nils277** [comment]
hmm sorry, that was my fault. Will make sure it is added in the next release.

**Comment by Nils277** [comment]
Fixed in version 1.3.1
