### ISSUE TITLE
KKAOSS_Central_Hub part has invalid entry for field researchTime.

### ISSUE THREAD

**Issue by Galenmacil** [Nils277/KerbalPlanetaryBaseSystems#18]
Excerpt from the log file:

_[LOG 17:51:27.062] PartLoader: Compiling Part 'PlanetaryBaseInc/BaseSystem/Parts/Command/CentralHub/Central_Hub/KKAOSS_Central_Hub'
[ERR 17:51:27.064] Invalid integer value! Field researchTime, value 7.39794000868 on object of type ModuleScienceConverter

[LOG 17:51:27.068] Starting the Dispatcher
[LOG 17:51:27.068] 
[ERR 17:51:27.097] Cannot find a PartModule of typename 'KKCrewPart'_

**Comment by Nils277** [comment]
Thanks, will fix that for the next version.
