### ISSUE TITLE
NRE on attempt to enter IVA mode 

### ISSUE THREAD

**Issue by kaa253** [Nils277/KerbalPlanetaryBaseSystems#2]
Steps to reproduce
Linux KSP 1.0.5 64 bit
Attach any two crewable KPBS parts together, add some crew and launch.
Transfer a crew member from one module into another (crew portraits disappear).
Press "C" to enter IVA game freezes.

Workaround - switch to space centre and then return to vessel OR install RPM

Suspect lines 45 and 50 of SurfaceStructuresCategory.cs may be cause or contribution where "GameData" is "Gamedata" in paths.

[Player.log.zip](https://github.com/Nils277/KerbalPlanetaryBaseSystems/files/204416/Player.log.zip)

**Comment by kaa253** [comment]
Saved a little bit after Player.log but not by much.
[KSP.log.zip](https://github.com/Nils277/KerbalPlanetaryBaseSystems/files/204659/KSP.log.zip)

**Comment by Nils277** [comment]
Thanks, i'll look into it.

**Comment by Nils277** [comment]
Does the NRE in the IVAs still happen for you in 1.1? I have tried it with 1.0.5 on another linux machine with 64bit at was not able to reproduce the error.

**Comment by Nils277** [comment]
Closed. Plugin code for IVA and KSP version have changed a lot since this bug has been reported. There are no signs of this be still being present in the curent version.
Will still have an eye out for any furher appearence.
