### ISSUE TITLE
K&K Garage Cover issues

### ISSUE THREAD

**Issue by HorusAK** [Nils277/KerbalPlanetaryBaseSystems#20]
Garage Cover part has some fitting issues. Images with descriptions can be viewed [here](http://imgur.com/a/Qhw6b)

Would be very nice to have a decoupler for K&K Garage Mk3 and 3.75m Adapter - the garage + garage cover shaped decoupler or even docking port (for multi use).

**Comment by Nils277** [comment]
Thanks for the info, will adapt the cover and adapter accordingly.

The decoupler for the garage parts sounds like a reasonable idea. The garage cover should be able to decouple itself from the garages by default. Will check if it still does.

Not sure about a docking port though. Have to thinkg about this ;)

**Comment by HorusAK** [comment]
Thanks for your work & community input.
Yes, the docking port idea was not good, so just forget it.

**Comment by Nils277** [comment]
Fixed with 1.3.6
