### ISSUE TITLE
Use CCK category for KIS inventories

### ISSUE THREAD

**Issue by ihsoft** [Nils277/KerbalPlanetaryBaseSystems#21]
[KIS](https://github.com/KospY/KIS) is now supporting Community Category Kit (https://github.com/KospY/KIS/issues/176). There is a dedicated category for KIS containers (tag: `cck-containers`). It makes sense to put there all the containers that are designed to hold other parts. As far as I can tell KKAOSS has at least two good candidates.

As a maintainer of KIS I'd suggest filling this new category with parts that are _primarily_ containers. E.g. `K&K Planetary Laboratory` that has KIS inventories is a wrong candidate since its primary function is not storing items but mining science. On the other hand, `K&K Container for Parts` looks like a perfect candidate for the new category since storing items is the only function of the part.

**Comment by Nils277** [comment]
Thanks for the suggestion, will do!

**Comment by Nils277** [comment]
fixed with 1.3.6
