### ISSUE TITLE
"K&K Ground Base [KIS]" doesn't show up in the editor

### ISSUE THREAD

**Issue by ihsoft** [Nils277/KerbalPlanetaryBaseSystems#22]
Due to latest change in KIS there is no KIS maintained category anymore, so any part with category set to "none" must have a CCK tag to be presented in some filter. Or, better, have both the category and the tag.

Specifically of this part I'd suggest category "Structural" (because it's clearly a structural element) and tag "cck-eva-items" (to show in EVA items filter).

**Comment by Nils277** [comment]
Thought i had added the "Structural" category in the last update.  Fixed with Commit 6613ab7015e6d47aaf2b19a26888c97aa62330c9
