### ISSUE TITLE
Kerbalism habitat surface/volume

### ISSUE THREAD

**Issue by ShotgunNinja** [Nils277/KerbalPlanetaryBaseSystems#26]
Here is a MM patch to specify custom surface/volumes for habitats. The values are deduced from bounding box if not specified, and that is okay. But user '_schrema_' has contributed hand-computed values for all habitats of KPBS. I figured it was appropriate to post these here. Best regards, and thank you for the extensive support.

**KPBS_MM_Kerbalism_Habitat.cfg**
```
@PART[KKAOSS_Habitat_MK2_g]:FOR[PlanetarySurfaceStructures]:NEEDS[Kerbalism&FeatureHabitat]:AFTER[Kerbalism]
{
	@MODULE[Habitat]
	{
		volume = 16.56
		surface = 23.29
		inflate = Habitat_MK2_deploy
		state = disabled
	}
	!MODULE[PlanetaryModule]:HAS[#animationName[Habitat_MK2_deploy]] {}
}
@PART[KKAOSS_Science_g]:FOR[PlanetarySurfaceStructures]:NEEDS[Kerbalism&FeatureHabitat]:AFTER[Kerbalism]
{
	@MODULE[Habitat]
	{
		volume = 19.32
		surface = 27.17
		inflate = Science_Deploy
		state = disabled
	}
	!MODULE[PlanetaryModule]:HAS[#animationName[Science_Deploy]] {}
}
@PART[KKAOSS_Greenhouse_g]:FOR[PlanetarySurfaceStructures]:NEEDS[Kerbalism&FeatureHabitat]:AFTER[Kerbalism]
{
	@MODULE[Habitat]
	{
		volume = 23.19
		surface = 32.61
		inflate = Greenhouse_Deploy
		state = disabled
	}
	!MODULE[PlanetaryModule]:HAS[#animationName[Greenhouse_Deploy]] {}
}
@PART[KKAOSS_Control_g]:FOR[PlanetarySurfaceStructures]:NEEDS[Kerbalism&FeatureHabitat]:AFTER[Kerbalism]
{
	@MODULE[Habitat]
	{
		volume = 3.68
		surface = 7.76
	}
}
@PART[KKAOSS_Cupola_g]:FOR[PlanetarySurfaceStructures]:NEEDS[Kerbalism&FeatureHabitat]:AFTER[Kerbalism]
{
	@MODULE[Habitat]
	{
		volume = 2.45
		surface = 5.17
	}
}
@PART[CRY-5000Freezer]:FOR[PlanetarySurfaceStructures]:NEEDS[Kerbalism&FeatureHabitat]:AFTER[Kerbalism]
{
	@MODULE[Habitat]
	{
		volume = 7.36
		surface = 15.53
	}
}
@PART[KKAOSS_Habitat_MK1_g]:FOR[PlanetarySurfaceStructures]:NEEDS[Kerbalism&FeatureHabitat]:AFTER[Kerbalism]
{
	@MODULE[Habitat]
	{
		volume = 7.36
		surface = 15.53
	}
}
@PART[KKAOSS_Central_Hub]:FOR[PlanetarySurfaceStructures]:NEEDS[Kerbalism&FeatureHabitat]:AFTER[Kerbalism]
{
	@MODULE[Habitat]
	{
		volume = 22.08
		surface = 23.56
	}
}
@PART[KKAOSS_airlock_mid_g]:FOR[PlanetarySurfaceStructures]:NEEDS[Kerbalism&FeatureHabitat]:AFTER[Kerbalism]
{
	@MODULE[Habitat]
	{
		volume = 1.84
		surface = 3.88
	}
}
@PART[KKAOSS_airlock_end_g]:FOR[PlanetarySurfaceStructures]:NEEDS[Kerbalism&FeatureHabitat]:AFTER[Kerbalism]
{
	@MODULE[Habitat]
	{
		volume = 1.71
		surface = 3.62
	}
}
```

**Comment by Nils277** [comment]
Thanks for the configs. They will be added with the next update!

**Comment by Nils277** [comment]
Whooopsy....should leave this open to not forget it!

**Comment by Nils277** [comment]
It seems there are still some problems with these configs. The Inflatable Parts (the first three) cannot be deployed with the Habitat Module in flight. Is there something (a resource or similar) that is needed to deplay the parts?

**Comment by Nils277** [comment]
For the time being i reactivated the module from KPBS but applied the volume and surface values.

**Comment by ShotgunNinja** [comment]
Sorry for the late reply...

Inflatable habitats are driven by pressure, so the user need Nitrogen and a PressureControl ECLSS module to inflate them on-the-field.

For various reasons, habitats can't be disabled when crew is inside.
Inflatable habitats start inflating as soon as they are enabled, and deflate as soon as they are disabled.
Inside the editor, pressurization/depressurization is symbolic and done instantly.

For these 3 reasons, if you put a kerbal in an inflatable part (in editor or in flight), it will start inflating. Likewise when you have somebody inside it can't be deflated.

**Comment by Nils277** [comment]
Outdated, not relevant anymore.
