### ISSUE TITLE
Making soe more parts on my own.

### ISSUE THREAD

**Issue by Andem6** [Nils277/KerbalPlanetaryBaseSystems#3]
Hi, I'm trying to mkae some KPBSalike parts for Tantares. The only issue is, I can't access your models to figure out how you did it. they are still .MU files in the source folder, and there aren't any programs that can read those. please help.

**Comment by Nils277** [comment]
Hi, i have not uploaded the source files for the models and textures to GitHub yet (Its 516 Files in 60 folders). But i linked some templates for some models and textures in the OP of the [KPBS thread](http://forum.kerbalspaceprogram.com/index.php?/topic/133606-10511pre-kerbal-planetary-base-systems-v106-107-for-prerelase-updated-23rd-march-16/): 
The links is this: [Templates](https://www.dropbox.com/s/ucgfk5mgaaahtar/Templates_V2.zip?dl=0)

If you'd like to use a specific model, you can either use the [MU Importer for Blender](http://forum.kerbalspaceprogram.com/index.php?/topic/40056-blender-mu-importexport-addon/) or send me a pm with the part you'd like to tinker with. I will send you a link to download it then.

**Comment by Andem6** [comment]
Ok, thanks. I use Wings 3D, and I was just hoping to peek around, see the structure you used to build the models. As for templates, Thank you soo much, they're probably all I need to export them.

**Comment by Nils277** [comment]
Pleasure to help :)
