### ISSUE TITLE
KSPedia_zh-cn.cfg not finished yet

### ISSUE THREAD

**Issue by bdangel1984** [Nils277/KerbalPlanetaryBaseSystems#35]
KSPEDIA zh-cn

//---The main page---
#LOC_KPBS.kspedia.main.title = Kerbal 星球建设系统
#LOC_KPBS.kspedia.main.subtitle = 在其它星球上建设将变得更简单
#LOC_KPBS.kspedia.main.desc = 诚实得说建设在某些时候仍然很困难。不过你能找到所有有关建设基地的信息.

//---Deployable Parts---
#LOC_KPBS.kspedia.deploy.title = 可部署部件
#LOC_KPBS.kspedia.deploy.subtitle = 一些可部署且可回收的部件.
#LOC_KPBS.kspedia.deploy.desc = 可部署部件初始是回收打包状态的，不过你可以在 飞机及火箭 的建设界面中部署它们，在活动的飞船上也行。被回收的部件无法装人。
#LOC_KPBS.kspedia.deploy.deploy = 部署
#LOC_KPBS.kspedia.deploy.retract = 回收
#LOC_KPBS.kspedia.deploy.parts.header = 接下来的3个部件可以被部署：
#LOC_KPBS.kspedia.deploy.parts.hab = 生活区 MK2:
#LOC_KPBS.kspedia.deploy.parts.hab.desc = 当此部件被部署的时候，它可以装入4位Kerbal星人。
#LOC_KPBS.kspedia.deploy.parts.greenhouse = 温室:
#LOC_KPBS.kspedia.deploy.parts.greenhouse.desc = 当温室被部署的时候，它可以装入2位Kerbal星人。
#LOC_KPBS.kspedia.deploy.parts.laboratory = 实验室:
#LOC_KPBS.kspedia.deploy.parts.laboratory.desc = 和温室一样，被部署的时候它可以装入2位Kerbal星人。.

//---Landing legs---
#LOC_KPBS.kspedia.legs.title = 着陆支架和着陆轮
#LOC_KPBS.kspedia.legs.subtitle = 有时可能你需要在Kerbal星建设你的基地。
#LOC_KPBS.kspedia.legs.legs = 着陆支架:
#LOC_KPBS.kspedia.legs.legs.bigfood = "Bigfoot" 支架
#LOC_KPBS.kspedia.legs.legs.bigfood.desc = "Bigfoot" 可以被安装在部件的面或对接点上。按<b>ALT</b>可以更轻松得将它们安装在对接点上。
#LOC_KPBS.kspedia.legs.legs.littlefood = "Little Bigfoot" 底面支架
#LOC_KPBS.kspedia.legs.legs.littlefood.desc = "Little Bigfoot" 部件可以安装在基础部件的底部。当没有足够空间的时候很有用。
#LOC_KPBS.kspedia.legs.wheels = 可连接滚轮:
#LOC_KPBS.kspedia.legs.wheels.desc = 当你在跑道上降落的时候它可以将你的基地变成一辆车。对于"Bigfoot" 这是最好的补充。它可以被随时回收或在不再需要的时候从部件上解下来。

//---Storage---
#LOC_KPBS.kspedia.storage.title = 仓储系列
#LOC_KPBS.kspedia.storage.subtitle = 满足你所有的仓储需求
#LOC_KPBS.kspedia.storage.desc = KPBS 提供了一个模板化的仓储系统，它可以按比例变化。 这个系统包含2类部件：储存架及容器
#LOC_KPBS.kspedia.storage.racks = 储存架:
#LOC_KPBS.kspedia.storage.racks.desc = 有3个基础尺寸的储存架，分别可以安装2，4，6个容器 ，另外还有2.5米直径的2种可用于火箭的尺寸，分别可以安装4，8个容器
#LOC_KPBS.kspedia.storage.container = 容器：
#LOC_KPBS.kspedia.storage.container.desc = 有两个尺寸的窗口，小的占用1个储存格， 大的要占用2格。
#LOC_KPBS.kspedia.storage.attach = 连接容器:
#LOC_KPBS.kspedia.storage.attach.desc = 为了将容器放入储存架， 你可以简单得使用上面的连接节点。你也可以使用KIS插件来接上或取下容器。

//---Config---
#LOC_KPBS.kspedia.config.title = 配置
#LOC_KPBS.kspedia.config.subtitle = 你可以指定部件所属的分类，只需要编辑 <b>GameData/PlanetaryBaseInc/KPBS_config.cfg</b>文件即可。
#LOC_KPBS.kspedia.config.subcategory = 自定义分类
#LOC_KPBS.kspedia.config.subcategory.desc = 当你将<b>showModCategory</b>设置成<b>true</b>的时候，此分类下的部件通过功能进行区分。
#LOC_KPBS.kspedia.config.lifesupport = 针对生命系统的过滤：
#LOC_KPBS.kspedia.config.lifesupport.desc = 默认情况下，Community Category Kit插件会将KPBS 船上的把所有的生命支持部件放在一个分类中
#LOC_KPBS.kspedia.config.functionfilter = 根据功能过滤的分类:
#LOC_KPBS.kspedia.config.functionfilter.desc = 当 <b>"Group all Parts in Function Filter"</b> 设置被打开的时候（你可以在游戏开始的难度设置中设置它） ，这个选项将在通过功能过滤的过滤器中增加一个分类，所有KPBS部件都将在下面。

//---Getting into space---
#LOC_KPBS.kspedia.storage.title = Getting into Space
#LOC_KPBS.kspedia.storage.subtitle = Before you can create a base an another planet, you have to get the parts into space first.
#LOC_KPBS.kspedia.storage.parts = KPBS has three parts that allow you to put the base parts on top of the rocket. The first one can be put on a 2.5m rocket and has two slots, the second one has three slots and can ba put on a 3.75m rocket. The third part is the adapter for a base part to the 1.25m rockets.
#LOC_KPBS.kspedia.storage.setup1 = On the right is an example of some base parts on top of a 2.5m rocket. The middle of the couplers have an additonal attachment point for beams or parts that should be on the top of the base parts, like parachutes or airbreaks.
#LOC_KPBS.kspedia.storage.setup1 = For best performance it is advised to put a protective shell around them.
#LOC_KPBS.kspedia.storage.bicoupler = Bi-Coupler with two slots
#LOC_KPBS.kspedia.storage.tricoupler = Tri-Coupler with three slots

//---Reentry and Landing---
#LOC_KPBS.kspedia.reentry.title = Reentry and Landing
#LOC_KPBS.kspedia.reentry.subtitle = Once in space it can only go down
#LOC_KPBS.kspedia.reentry.desc = For the reentry into an atmosphere the following configuration proves to be the most reliable:
#LOC_KPBS.kspedia.reentry.parachute = Parachute
#LOC_KPBS.kspedia.reentry.airbrake = Airbrakes
#LOC_KPBS.kspedia.reentry.wheels = Wheels and Legs
#LOC_KPBS.kspedia.reentry.heatshield = Heatshield
#LOC_KPBS.kspedia.reentry.control = Control Unit
#LOC_KPBS.kspedia.reentry.separator = Stack separator
#LOC_KPBS.kspedia.reentry.text1 = The shield protects you from the heat while the airbreaks slow the craft down and keep it stable. When save, deploy the big parachute.\n You can then separate both sides and land them safely with the landing engines and parachutes.
#LOC_KPBS.kspedia.reentry.text2 = Keep in mind that you need a control unit on each vessel!
#LOC_KPBS.kspedia.reentry.landing.title = Landing without atmosphere
#LOC_KPBS.kspedia.reentry.landing.text1 = When there is no atmosphrer use a bigger engine in place if the heatshield to slow down. The Meerkat landing engine will help you to land the craft savely. On planets with higher gravity a skycrane can be of help.
#LOC_KPBS.kspedia.reentry.landing.text2 = You also might want to separate both sites in orbit and land them separately.

//---Corridors---
#LOC_KPBS.kspedia.corridors.title = Corridors
#LOC_KPBS.kspedia.corridors.subtitle = Dynamic parts to connect your base
#LOC_KPBS.kspedia.corridors.desc = With KPBS comes a variety of corridor parts that you can use to connect your base or also build space- stations. The corridor parts have a special feature:\n They adapt their appearance to where you have connected other parts to them. This means that you only need one corridor part to build everything. 
#LOC_KPBS.kspedia.corridors.connect = Once connected, the corridor changes it appearance. It can have all kind of shapes: straight corridor, corner, crossway, T-shape. This behaviour is also present when connecting parts via KIS. So you can create your base directly at the planet without having to puzzle over every detail.
#LOC_KPBS.kspedia.corridors.base = There is also an adapting part with the profile of the base parts of you'd more like the base to look like one single piece. 
#LOC_KPBS.kspedia.corridors.note = Note: When you have KAS installed there is also a flexible corridor available.

**Comment by Nils277** [comment]
Thanks a lot! Will add it to KPBS when finished ;)

**Comment by Nils277** [comment]
Comitted the file with the first translation into the repository: https://github.com/Nils277/KerbalPlanetaryBaseSystems/commit/5bfb7882424e071c74b002124f4bb8b3e1258b80

**Comment by Nils277** [comment]
Hey, i just wanted to inform you, that a member from the forum [Acea](http://forum.kerbalspaceprogram.com/index.php?/profile/98766-acea/) finished the chinese translation for KSPedia and is also seemingly working on the translation for the parts. 
Just wanted to inform you about that so both of you might talk about the translation and some of the work is not done by both of you.
