### ISSUE TITLE
A couple of localization bugs.

### ISSUE THREAD

**Issue by doktorjet** [Nils277/KerbalPlanetaryBaseSystems#40]
1. #LOC_KPBS.greenhousecontainer.description is still english when game itself is russian.
Reason: ModuleManager string in Container_Algae.cfg: "@description = A small algae form to produce fertilizer that are needed to grow food. Do not eat the fertilizer, they taste aweful."
BTW, this string has a typo anyway.

2. Fertilizer container description for TAC LS is incorrect. It mentions USI LS Noms, while it shouldn't (TAC LS uses Food instead of Noms).

**Comment by Nils277** [comment]
Will fix those issues. Thanks for bringing them up

**Comment by Nils277** [comment]
fixed via: https://github.com/Nils277/KerbalPlanetaryBaseSystems/commit/a1fdcca58776977a7adcf08e84a114e910aee146
Strings would need translation though.

**Comment by doktorjet** [comment]
For greenhouse container:
Current #LOC_KPBS.greenhousecontainer.description is pretty fine for TAC LS.

For algae container:
"Малая водорослевая ферма производит удобрения, необходимые для выращивания еды. Не ешьте удобрения, они невкусные."

**Comment by Nils277** [comment]
Fixed via ce49c87
