### ISSUE TITLE
Add Decoupler FX to garage_decoupler_g 

### ISSUE THREAD

**Issue by wile1411** [Nils277/KerbalPlanetaryBaseSystems#47]
Adding it would fix an error that occurs in the log file when the game loads,
Code you've used in other parts for this pack:

sound_vent_large = decouple
fx_gasBurst_white = 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, decouple

**Comment by Nils277** [comment]
sorry, forgot to fix this on in the last update. Will make sure to do so in the next one.

**Comment by Nils277** [comment]
Fixed with e4967d3
