### ISSUE TITLE
USI MKS + ELP support

### ISSUE THREAD

**Issue by doktorjet** [Nils277/KerbalPlanetaryBaseSystems#52]
When both **USI MKS** and **Extraplanetary Launchpads** are installed, ELP is automagically reconfigured to use USI resources (_MaterialKits_ and _SpecializedParts_), while **KPBS** parts still store (and maybe still use) _RocketParts_.
https://github.com/UmbraSpaceIndustries/MKS/wiki/Functions-(Extraplanetary-Launchpads)

**Comment by Nils277** [comment]
I'm not quite sure of this should rather be an issue and/or feature request for the [KPBS/MKS Integration Pack](https://github.com/DanStaal/KPBStoMKS)

You are right that everything should work as intentended when other mods are installed. But a mod that changes the behavior of another mod in such a drastic way is a borderline case. It would be way to time consuming and exhausting to look out for all mods that change the behaviour of other mods.
To be honest my opinion of mods that change the behavior of another mod and essentially force all other mods to also take that changes into account is not very high.

Will probably add these changes though...

**Comment by Nils277** [comment]
Closing this one. As said, KPBS does not support MKS by itself but there is the [KPBS/MKS Integration Pack](https://github.com/DanStaal/KPBStoMKS) which should handle this case.
It would be way too time consuming to support that other mods add the behaviour of mods supported by KPBS. Especially a very complex one like MKS.

**Comment by Grimmas** [comment]
I've actually been working on my own MKS patch for KPBS and didn't know about Dan's work. Sadly, it seems like he's moved on. There hasn't been any activity in four years, and large parts of the patch are outdated. 

My patch is meant to be much more light-weight, too, adding just the basic support without rewriting all KPBS systems to use all MKS functionality. I hope you'll be willing to take a look at it. If it's really not your thing then I can just put it into a separate repo later.

**Comment by Nils277** [comment]
Thanks, will add the patch to KPBS! It's always good when the mods at least play nice together 👍
