### ISSUE TITLE
Weird Sentenses In Localization file

### ISSUE THREAD

**Issue by EthanWang706** [Nils277/KerbalPlanetaryBaseSystems#59]
`        //the following two texts are combined to: 
        //    Crew Capacity
        //    Retracted:  <NUM1>
        //    Deployed:   <NUM2> `
In those part, it's only a number, but there's 2 space between <NUM> and : 
I don't know if this is a issue, or it needs to be like this.

**Comment by Nils277** [comment]
The different number of spaces are there to align the numbers and should somehow represent how the text will look like in the VAB/SPH. It is simply a cosmetic thing ;-)
