### ISSUE TITLE
TAC Life Support    I DON'T FIND  water drill 

### ISSUE THREAD

**Issue by dxqiuxin** [Nils277/KerbalPlanetaryBaseSystems#69]
USE  TAC Life Support  the water drill  error loading    I DON'T FIND  water drill    THIS IS like this?

I'M Engish very poor......

用了TAC Life Support 没有找到水钻，这是就这样设置的还是缺少哪个MOD？

KerbalPlanetaryBaseSystems  IS VERY GOOD MOD。。。THANK YOU。。

**Comment by Nils277** [comment]
fixed in fc6756a49745fd4c79362f40c90f3f71797743cf
