### ISSUE TITLE
Container_Greenhouse.cfg, CTT & USI-LS

### ISSUE THREAD

**Issue by Cooper42** [Nils277/KerbalPlanetaryBaseSystems#75]
Currently the CTT support for this part is overridden by the USI-LS support for this part. Which leads to it being placed in Survivability, but the USI-LS patch for CTT puts its earliest greenhouse in Hydroponics. 

USI-LS also puts the smallest Mulch & Fertilizer storage behind Hydroponics, so currently this means this mod allows for Mulch, Fertilizer & Greenhouse by Storage Tech, before USI-LS intends it when using CTT.

I would suggest the easiest solution, as there's probably . reason for the current order, is to simply add the following to the very end of Container_Greenhouse.cfg:

`//------------------USI-LS & COMMUNITY TECHTREE-------------------------`
`@PART[KKAOSS_LS_container_greenhouse]:FOR[PlanetarySurfaceStructures]:NEEDS[CommunityTechTree&USILifeSupport]`
`{`
`    @TechRequired = hydroponics`
`}`

**Comment by Nils277** [comment]
Thanks, will be fixed in the next update!
