### ISSUE TITLE
CLS is broken by new Flexible Corridor.

### ISSUE THREAD

**Issue by TonkaCrash** [Nils277/KerbalPlanetaryBaseSystems#85]
Connected Living Spaces does not see spaces connected by new flexible corridor to docking port as connected. [Related forum post](https://forum.kerbalspaceprogram.com/index.php?/topic/133606-15x-kerbal-planetary-base-systems-v166-15-november-2018/&do=findComment&comment=3488679)

**Comment by Nils277** [comment]
This will be fixed once a new version of KAS is online that allows to use the flexible corridor on both ends.

**Comment by Nils277** [comment]
Fixed since 726fb1f
