### ISSUE TITLE
Mod Patch for Extra Planetary Launchpads is outdated

### ISSUE THREAD

**Issue by ubuntufreakdragon** [Nils277/KerbalPlanetaryBaseSystems#86]
Some time ago this bug was fixed in EL, resulting in the partconfig of smelters being heavily changed.
The mod compatibility patch still uses the old config.
https://github.com/taniwha/Extraplanetary-Launchpads/issues/144

**Comment by Critter79606** [comment]
The KKAOSS_Smelter doesn't generate any heat, and thus doesn't convert anything.  For now, I've created a patch file to fix mine (I don't like editing original files).  Here is the patch I created that fixes the part.

@PART[KKAOSS_Smelter]:NEEDS[Launchpad]:AFTER[PlanetarySurfaceStructures]
{
    !MODULE[ELConverter],* {}
    
    MODULE {
		name = ELConverter
		ConverterName = Smelter
		EVARange = 3
		StartActionName = #LOC_KPBS.smelter.metal.start
		StopActionName = #LOC_KPBS.smelter.metal.stop
		ConverterRecipe = LFOFiredSmelter
		Rate = 1
		efficiency = 273.15, 0
		efficiency = 1873, 1

		AutoShutdown = false
		GeneratesHeat = true
	}

	MODULE {
		name = ELConverter
		ConverterName = Scrap Metal Remelter
		EVARange = 3
		StartActionName = #LOC_KPBS.smelter.scrap.start
		StopActionName = #LOC_KPBS.smelter.scrap.stop
		ConverterRecipe = LFOFiredRemelter
		Rate = 1
		efficiency = 273.15, 0
		efficiency = 1873, 1

		AutoShutdown = false
		GeneratesHeat = true
	}

	MODULE {
		name = ELCoreHeat
		CoreTempGoal = 1873
		CoreToPartRatio = 0.1
		CoreTempGoalAdjustment = 0
		CoreEnergyMultiplier = 0.1
		HeatRadiantMultiplier = 0.05
		CoolingRadiantMultiplier = 0
		HeatTransferMultiplier = 0.01
		CoolantTransferMultiplier = 0.01
		radiatorCoolingFactor = 1
		radiatorHeatingFactor = 0.05
		MaxCalculationWarp = 1000
		CoreShutdownTemp = 4000
		MaxCoolant = 0
	}
}

**Comment by Nils277** [comment]
Thanks will take care of that in the next update

**Comment by Nils277** [comment]
fixed in 90ab7a5
