### ISSUE TITLE
Wrong Module in CRY50000RPMMM.cfg

### ISSUE THREAD

**Issue by 4x4cheesecake** [Nils277/KerbalPlanetaryBaseSystems#88]
The ModSupport patch CRY50000RPMMM.cfg adds a wrong module to the CRY-5000Freezer:
Right now, it says:
MODULE
{
    name = KPBSTransparendPodHelper
    hiddenOverlayTransformNames = JSIATPwindowLeft|JSIATPwindowRight
}

but it must be:
MODULE
{
    name = **Module**KPBSTransparendPodHelper
    hiddenOverlayTransformNames = JSIATPwindowLeft|JSIATPwindowRight
}

Also, the @MODULE[DeepFreezer] looks kinda unnecessary ;)

**Comment by Nils277** [comment]
Thanks, will be fixed in the next release

**Comment by Nils277** [comment]
Fixed since b1cf11a
