### ISSUE TITLE
"k&k science container" missing function: "restore" with scientist on eva

### ISSUE THREAD

**Issue by menachg** [Nils277/KerbalPlanetaryBaseSystems#92]
on "KKAOSS.ScienceJr.Tank" after transmitting data from materials bay a scientist should be able to "restore materials bay" on eva.
but it does not show up as on option.

**Comment by HSJasperism** [comment]
Have you tried getting closer? The part's EVA interaction range is 1.2 (the default Science Jr. is at 1.85). It can be difficult to find the right spot on Kerbin and other high gravity bodies, but moons and Duna should be fine.

**Comment by menachg** [comment]
I'll do some more tests and see

**Comment by Nils277** [comment]
Hmm, did the range get extended in KSP in some update?
Will increase the distance to 1.8 for better usability

**Comment by menachg** [comment]
well after a simple test conducted I can confirm the option "restore materials bay" is accessible so I don't know why it didn't show me this in game.
but I'm glad I stumbled here on an inconsistency I wasn't aware of,I guess :)

**Comment by Nils277** [comment]
fixed with 726fb1f9deba1bace09ad7ac68dcab4549fc46e7
